agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView,AgentHistoryView


app_name="agents"

urlpatterns=[
    path("",AgentListView.as_view(),name="agent-list"),
    path("create/",AgentCreateView.as_view(),name='agent-create'),
    path('<int:pk>/detail',AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete',AgentDeleteView.as_view(), name='agent-delete'),
    path('<int:pk>/history',AgentHistoryView.as_view(), name='agent-history'),
    ]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,

    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    LeadRegisterView,

    )
app_name="leads"

urlpatterns=[

path('',LeadListView.as_view(), name='lead-list'),
path('<int:pk>/',LeadDetailView.as_view(), name='lead-detail'),
path('<int:pk>/register/',LeadRegisterView.as_view(), name='lead-register'),
path('<int:pk>/update',LeadUpdateView.as_view(), name='lead-update'),
path('<int:pk>/delete',LeadDeleteView.as_view(), name='lead-delete'),

path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name='assign-agent'),



path('categories/',CategoryListView.as_view(),name='category-list'),
path('categories/<int:pk>/',CategoryDetailView.as_view(),name='category-detail'),
path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='lead-category-update'),
path('creategories/<int:pk>/update',CategoryUpdateView.as_view(), name='category-update'),
path('create-category/',CategoryCreateView.as_view(), name='category-create'),
path('categories/<int:pk>/delete',CategoryDeleteView.as_view(), name='category-delete'),


]

# using name - its like name given to the url. so where we need to mention this url we can use the name in place of the url.
# /leads/create = lead_create -> without this if we did any change in url we need to chamge the url in every place.
# /leads-YT/create now we need to change this url every where because /leads/create is not same as /leads-YT/create,
# with using name we can just udate at one place and the name value will get updated in every palce.9

travel/urls.py
from django.contrib import admin
from django.contrib.auth.views import (LoginView,LogoutView,PasswordResetView, 
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView,
)

from django.urls import path
from leads.views import (
LandingPageView,
SignupView,
)

from destination.views import DashboardView

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name="landing-page"),
    path('dashboard/',DashboardView.as_view(), name="dashboard"),
    path('leads/',include('leads.urls', namespace="leads")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('agents/',include('agents.urls',namespace="agents")),
    path('reset-password/',PasswordResetView.as_view(),name='reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_done'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    
    path('destination/',include('destination.urls', namespace="destination")),



]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    path('/leads',include('leads.urls', namespace="leads")) this means if we request /leads than it will start looking for url in leads.url folder.

leads/forms.py
from django import forms
from .models import Lead,Agent,Category

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,UsernameField


from destination.models import Destination

User=get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model=Lead
        fields= (
        'first_name',
        'last_name',
        'age',
        'agent',
        'destination',
        'phone_number',
        'email',
        'profile_picture'
                )
    def __init__(self, *args, **kwargs):
       
        if 'curr_destination_id' in kwargs:
            curr_destination_id2 = kwargs.pop('curr_destination_id')
            super(LeadModelForm, self).__init__(*args, **kwargs)

            # To assign the destination
            destination_instance = Destination.objects.filter(id=curr_destination_id2).first()
            self.fields['destination'].initial = destination_instance.place_name if destination_instance else None

            # dynamically add the choice filed.
            filtered_users = User.objects.filter(destination_assign_id=curr_destination_id2)
            filtered_agents = [user.agent for user in filtered_users if user.agent]

            self.fields['agent'].queryset = Agent.objects.filter(pk__in=[agent.pk for agent in filtered_agents])
        else:
            super(LeadModelForm, self).__init__(*args, **kwargs)
        
      

class LeadForm(forms.Form):
    first_name=forms.CharField()
    last_name=forms.CharField()
    age=forms.IntegerField(min_value=0)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=User
        fields=("username",)
        field_Classes={'username': UsernameField}

class AssignAgentForm(forms.Form):
    agent=forms.ModelChoiceField(queryset=Lead.objects.none())

    def __init__(self, *args, **kwargs):
    
      
        # this is to find the lead and its destination
        pk=kwargs.pop("pk")
        desti_check=Lead.objects.filter(id=pk).first()
        name=desti_check.destination

        # now we have the name of the destination and dron destination table i will get the id of the destination

        desti_id_check=Destination.objects.filter(place_name=name).first()
        id_check=desti_id_check

        # now i will filter out the agents to which above specific destination was assigned.

                

        super(AssignAgentForm, self).__init__(*args, **kwargs)
        filtered_users = User.objects.filter(destination_assign_id=id_check)
        filtered_agents = [user.agent for user in filtered_users if user.agent]

        self.fields['agent'].queryset = Agent.objects.filter(pk__in=[agent.pk for agent in filtered_agents])


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields={
            'category'
        }

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=(
            'name',

        )

leads/views.py
from typing import Any

from django.shortcuts import render, redirect,reverse
from django.core.mail import send_mail

from .models import Lead, Agent,Category
from .forms import ( LeadModelForm,
                    LeadCategoryUpdateForm,
                    CustomUserCreationForm,
                    AssignAgentForm,
                    CategoryModelForm,                           
)
from django import forms

from django.db.models import Q

from django.contrib import messages
from django.views.generic import (TemplateView,ListView,
UpdateView,DeleteView,DetailView,CreateView,FormView)
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OragniserLoginRequiredMixin

from destination.models import Destination

import datetime

# Create your views here.

class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")



class LandingPageView(TemplateView):
   template_name="landing.html"


class LeadListView(LoginRequiredMixin,ListView):
   template_name="leads/lead_list.html"
   context_object_name="leads"

   def get_queryset(self):
      user=self.request.user
     
      if user.is_organisor:
            queryset = Lead.objects.all()
            
      else:
            queryset = Lead.objects.filter(
                agent__isnull=False
            )
            # filter for the agent that is logged in
            queryset = queryset.filter(agent__user=user)
      return queryset
   
   def get_context_data(self,**kwargs):
      context=super(LeadListView,self).get_context_data(**kwargs)
      user=self.request.user
      if user.is_organisor:
         queryset=Lead.objects.filter( agent__isnull=True)
         context.update({
            "unassigned_leads":queryset, 
         })
      else:
         finag=Agent.objects.filter(user_id=user.id).first()
         usid=finag.id
   
         context.update({
            "usid":usid 
         })
  
      return context
   

class LeadDetailView(LoginRequiredMixin,DetailView):
   template_name="leads/lead_detail.html"
   context_object_name="lead"
   #it will autometically pickup the obectt for id=pk.

   def get_queryset(self):
      destination_pk = self.kwargs['pk']
      # Filter the Destination queryset based on the destination_pk
      queryset = Lead.objects.filter(id=destination_pk)
      return queryset




class LeadRegisterView(CreateView):
   template_name="leads/lead_register.html"
   form_class=LeadModelForm
   context_object_name="destination"


   def get_success_url(self):
        return reverse("dashboard")
   
   def form_valid(self,form):
      lead = form.save(commit=False)
      # Get the destination_pk from the URL
      destination_pk = self.kwargs['pk']
      # Filter the Destination queryset based on the destination_pk
      destination = Destination.objects.get(id=destination_pk)

      lead.destination = destination.place_name
      lead.save()
      message = "You are now registered for {} trip destination".format(destination.place_name)


      send_mail(
         subject="Registration completed",
          message=message,
         from_email="test@test.com",
         recipient_list=["test2@test2.com"]
      )
      return super(LeadRegisterView, self).form_valid(form)

   def get_context_data(self, **kwargs):
      context = super(LeadRegisterView, self).get_context_data(**kwargs)
      destination_pk = self.kwargs['pk']
      # Retrieve data from the database, for example
      destination = Destination.objects.get(id=destination_pk)
      queryset_data= destination.place_name
      context.update({'curr_destination':queryset_data})
      return context
   
   def get_form_kwargs(self):
      kwargs = super(LeadRegisterView, self).get_form_kwargs()
      kwargs['curr_destination_id'] = self.kwargs['pk']  # Pass the curr_destination to the form
      return kwargs

class LeadUpdateView(LoginRequiredMixin
,UpdateView):
   template_name="leads/lead_update.html"
   form_class=LeadModelForm
   model=Lead

   def get_success_url(self):
      return reverse("leads:lead-list")

   def get_queryset(self):
      lead_pk = self.kwargs['pk']
      return Lead.objects.filter(id=lead_pk)
   
   def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this lead")
        return super(LeadUpdateView, self).form_valid(form)

   
   def get_form(self, form_class=None):
      form = super(LeadUpdateView, self).get_form(form_class) 
      # if 'agent' in self.fields:

      previous_instance = self.get_object()

      # Access the value of a specific field from the previous instance
      find_category = previous_instance.category_id

      check_Category=Category.objects.filter(id=find_category).values('name').first()
      if check_Category and check_Category["name"] == "Completed":
         form.fields['first_name'].widget.attrs['disabled'] = True
         form.fields['last_name'].widget.attrs['disabled'] = True
         form.fields['phone_number'].widget.attrs['disabled'] = True


      form.fields['agent'].widget.attrs['disabled'] = True
      form.fields['agent'].help_text = 'This field is not editable.'

      form.fields['destination'].widget.attrs['readonly'] = True
      form.fields['destination'].help_text = 'This field is not editable.'

      return form





class LeadDeleteView(OragniserLoginRequiredMixin
,DeleteView):
   template_name="leads/lead_delete.html"

  
   def get_success_url(self):
      return reverse("leads:lead-list")
   def get_queryset(self):
      lead_delete_pk = self.kwargs['pk']
      return Lead.objects.filter(id=lead_delete_pk)
   
    

   



class AssignAgentView(OragniserLoginRequiredMixin,FormView):
   template_name="leads/assign_agent.html"
   form_class=AssignAgentForm
   
   def get_form_kwargs(self,**kwargs):
      kwargs=super(AssignAgentView,self).get_form_kwargs(**kwargs)
      pk = self.kwargs.get('pk')
      kwargs.update({
         # "request":self.request,
         "pk":pk
      })
      return kwargs
  

   def get_success_url(self):
      return reverse("leads:lead-list")

   def form_valid(self,form):
      agent=form.cleaned_data["agent"]
      lead=Lead.objects.get(id=self.kwargs["pk"])
      lead.agent=agent
      lead.save()
      return super(AssignAgentView,self).form_valid(form)



class CategoryListView(LoginRequiredMixin,ListView):
   template_name ="leads/category_list.html"
   context_object_name="category_list"
   def get_queryset(self):
      user=self.request.user
      if user.is_organisor:
         queryset=Category.objects.filter(organisation=user.userprofile)
      else:
         queryset=Category.objects.filter(organisation=user.agent.organisation)
      return queryset
   
   
   
   def get_context_data(self, **kwargs: Any):
      context=super(CategoryListView,self).get_context_data(**kwargs)
      queryset=Lead.objects.all()
   
      context.update({
         "Completed":queryset.filter(category__name='Completed').count(),
         "NotCompleted":queryset.filter(Q(category_id=2) | Q(category__isnull=True)).count()

      })
      return context
      


class CategoryDetailView(LoginRequiredMixin,DetailView):
   template_name="leads/category_detail.html"
   content_object_name="category"


   def get_queryset(self):
      user=self.request.user
      if user.is_organisor:
         queryset=Category.objects.filter(organisation=user.userprofile)
      else:
         queryset=Category.objects.filter(organisation=user.agent.organisation)
      return queryset
  

class LeadCategoryUpdateView(LoginRequiredMixin,UpdateView):
   template_name="leads/lead_category_update.html"
   form_class=LeadCategoryUpdateForm

   def get_success_url(self):
      return reverse("leads:lead-detail", kwargs={"pk":self.get_object().id})

   def get_queryset(self):
      user=self.request.user
      pk = self.kwargs.get('pk')
      if user.is_organisor:
         queryset=Lead.objects.filter(id=pk)
      else:
         queryset=Lead.objects.filter(id=pk)
      return queryset
   
   def form_valid(self, form):
        lead_before_update = self.get_object()
        instance = form.save(commit=False)
        converted_category = Category.objects.get(name="Completed")
        if form.cleaned_data["category"] == converted_category:
            # update the date at which this lead was converted
            if lead_before_update.category != converted_category:
                # this lead has now been converted
                instance.converted_date = datetime.datetime.now()
        instance.save()
        return super(LeadCategoryUpdateView, self).form_valid(form)


   def get_form(self, form_class=None):
      form = super(LeadCategoryUpdateView, self).get_form(form_class) 
      previous_instance = self.get_object()

      # Access the value of a specific field from the previous instance
      find_category = previous_instance.category_id
    
      check_Category=Category.objects.filter(id=find_category).values('name').first()
      if check_Category and check_Category["name"] == "Completed":
         form.fields['category'].widget.attrs['disabled'] = True
      return form
         

class CategoryCreateView(LoginRequiredMixin,CreateView):
   template_name="leads/category_create.html"
   form_class=CategoryModelForm


   def get_success_url(self):
        return reverse("leads:category-list")

   def form_valid(self,form):
      category=form.save(commit=False)
      category.organisation=self.request.user.userprofile
      category.save()
      return super(CategoryCreateView,self).form_valid(form)

class CategoryUpdateView(LoginRequiredMixin,UpdateView):
   template_name="leads/category_update.html"
   form_class=CategoryModelForm


   def get_success_url(self):
        return reverse("leads:category-list")


   
   def get_queryset(self):
      user=self.request.user

leads/templates/leads/category_detail.html
{% extends "base.html" %}
{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
        <a href="{% url 'leads:category-update' category.pk %}" class="hover:text-blue-500">Update</a>
        <a href="{% url 'leads:category-delete' category.pk %}" class="hover:text-blue-500">Delete</a>
      </div>
     
      <a href="{% url 'leads:category-list' %}" class= "lg:mt-2 xl:mt-0 flex-shrink-0 inline-flex text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded">Back</a>
      <div class="py-4 lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl ">First Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Email</th>
            </tr>
          </thead>
          <tbody>
  
            {% for lead in category.leads.all %}
               <tr>
                    <td class=""px-4 py-3>
                    <a class=" hover:text-blue-500" href="{% url 'leads:lead-detail' lead.pk %}">
                        {{ lead.first_name }}
                    </td>
                    <td class=""px-4 py-3">{{ lead.last_name }}</td>
                    <td class=""px-4 py-3">{{ lead.email }}</td>
               </tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Trip Status</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            These categories segment the Trips
        </p>
         <a href="{% url 'leads:category-create' %}" class="hover:text-blue-500">Create a category</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-tl rounded-bl">Trip</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200">Count</th>
            </tr>
          </thead>
          <tbody>
            {% for category in category_list %}
              <tr>
                  <td class="px-4 py-3">
                    <a class="hover:text-blue-500" href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
                  </td>
                  {% if category.name == 'Completed' %}
                    <td class="px-4 py-3">{{ Completed }}</td>
                  {% else %}
                    <td class="px-4 py-3">{{ NotCompleted }}</td>
                  {% endif %}
              </tr> 
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

leads/templates/leads/home_page.html
{% extends "base.html" %}
{% block content %}
    <h1>Hello world</h1>
    <p>Welcome to {{ leads }}</p>
{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
                <a href = "{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
                <a  href = "{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 border-gray-300 py-2 text-lg px-1">Category</a>
                <a href = "{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
        </div>
          <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- {{ form.as_p }} -->
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 font rounded-md"  style="font-family: 'Arial', sans-serif;">Submit</button>
          </form>
        </div>
       
    </div>
  </section>
  

{% endblock content%}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-3xl text-gray-800">Leads</h1>
                {% if request.user.is_organisor %}
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category-list' %}">
                        View categories
                    </a>
                {% endif %}
            </div>
            {% if  request.user.is_agent %}
                <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center"><a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-detail' pk=usid %}">Agent History</a></nav>
            {% endif %}
        </div>  
        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Last Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                             Agent
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Category
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.last_name }}
                                </td>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.agent }}
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {% if lead.category|stringformat:"s" == "Completed"  %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ lead.category.name }}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Not completed
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'leads:lead-update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Update
                                    </a>
                                </td>
                            </tr>

                        {% empty %}

                        <p>There are currently no leads</p>
                        
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div> 
 {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned Agent to leads </h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.first_name }} {{ lead.last_name }}
                            </h2>
                            <p style=" color: red;">Destination</p>
                            <p class="leading-relaxed text-base">
                                {{ lead.destination }}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'leads:lead-category-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}