agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView,AgentHistoryView


app_name="agents"

urlpatterns=[
    path("",AgentListView.as_view(),name="agent-list"),
    path("create/",AgentCreateView.as_view(),name='agent-create'),
    path('<int:pk>/detail',AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete',AgentDeleteView.as_view(), name='agent-delete'),
    path('<int:pk>/history',AgentHistoryView.as_view(), name='agent-history'),
    ]

destination/urls.py
from django.urls import path
from .views import (
    DestinationAddView,
    DestinationDetail,
    DestinationUpdate,
    DestinationDelete,
    )


app_name="destination"

urlpatterns=[

    path("create/",DestinationAddView.as_view(),name="destination-create"),
    path("<int:pk>/",DestinationDetail.as_view(),name="destination-detail"),
    path("<int:pk>/update/",DestinationUpdate.as_view(),name="destination-update"),
    path("<int:pk>/delete/",DestinationDelete.as_view(),name="destination-delete")
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,

    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    LeadRegisterView,

    )
app_name="leads"

urlpatterns=[

path('',LeadListView.as_view(), name='lead-list'),
path('<int:pk>/',LeadDetailView.as_view(), name='lead-detail'),
path('<int:pk>/register/',LeadRegisterView.as_view(), name='lead-register'),
path('<int:pk>/update',LeadUpdateView.as_view(), name='lead-update'),
path('<int:pk>/delete',LeadDeleteView.as_view(), name='lead-delete'),

path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name='assign-agent'),



path('categories/',CategoryListView.as_view(),name='category-list'),
path('categories/<int:pk>/',CategoryDetailView.as_view(),name='category-detail'),
path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='lead-category-update'),
path('creategories/<int:pk>/update',CategoryUpdateView.as_view(), name='category-update'),
path('create-category/',CategoryCreateView.as_view(), name='category-create'),
path('categories/<int:pk>/delete',CategoryDeleteView.as_view(), name='category-delete'),


]

# using name - its like name given to the url. so where we need to mention this url we can use the name in place of the url.
# /leads/create = lead_create -> without this if we did any change in url we need to chamge the url in every place.
# /leads-YT/create now we need to change this url every where because /leads/create is not same as /leads-YT/create,
# with using name we can just udate at one place and the name value will get updated in every palce.9

travel/urls.py
from django.contrib import admin
from django.contrib.auth.views import (LoginView,LogoutView,PasswordResetView, 
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView,
)

from django.urls import path
from leads.views import (
LandingPageView,
SignupView,
)

from destination.views import DashboardView

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name="landing-page"),
    path('dashboard/',DashboardView.as_view(), name="dashboard"),
    path('leads/',include('leads.urls', namespace="leads")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('agents/',include('agents.urls',namespace="agents")),
    path('reset-password/',PasswordResetView.as_view(),name='reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_done'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    
    path('destination/',include('destination.urls', namespace="destination")),



]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    path('/leads',include('leads.urls', namespace="leads")) this means if we request /leads than it will start looking for url in leads.url folder.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    
    
</head>
<body>
    <div class="max-w-7xl mx-auto" >
        {% include 'navbar.html' %}
        {% block content %}
       
        {% endblock content %}
        
</div>
    {% include "scripts.html" %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col">
        <div class="h-1 bg-gray-200 rounded overflow-hidden">
          <div class="w-24 h-full bg-indigo-500"></div>
        </div>
      <br>
      
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      
        
  
        {% if request.user.is_organisor %}
          <a href="{% url 'destination:destination-create' %}" class="mr-5 hover:text-gray-900">Add Destinations</a>
        {% endif %}
      </nav>
    
        <div class="flex flex-wrap sm:flex-row flex-col py-6 mb-12">
          
          <h1 class="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">Wanderer</h1>
          <p class="sm:w-3/5 leading-relaxed text-base sm:pl-10 pl-0">Travel is not just a movement; it's a dance with the unknown, a melody of discovery, and a symphony of wonder that plays in the heart of every adventurer.</p>

          
      </div>
      <div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
        {% for destination in destinations %}
          <div class="p-4 md:w-1/3">
            <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden"> 
              {% if destination.place_picture %}
               <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{ destination.place_picture.url }}" alt="blog">
              {% else %}
              <img class="lg:h-48 md:h-36 w-full object-cover object-center" alt="hero" src="{% static 'images/moun.jpg' %}">
              {% endif %}
              <div class="p-6">
                {% if request.user.is_organisor %}
                  <a href="{% url 'destination:destination-update' destination.pk %}" class="text-white bg-indigo-500 border-0  px-2 focus:outline-none hover:bg-indigo-600 rounded">Update</a>
                {% endif %}
                <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">{{ destination.place_status }}</h2>
                <h1 class="title-font text-lg font-medium text-gray-900 mb-3">{{ destination.place_name }}</h1>
                  
                <p class="leading-relaxed mb-3">{{ destination.place_description }}</p>
                <div class="flex items-center flex-wrap">
                  
                  <a href="{% url 'leads:lead-register' destination.pk  %}" class="inline-flex text-white bg-indigo-500 border-0 py-1 px-4 focus:outline-none hover:bg-indigo-600 rounded">Register</a>
                  <a class="text-indigo-500 inline-flex items-center ml-4" href="">Learn More
                    <!-- To add link to Learn more href="{% url 'destination:destination-detail' destination.pk %}" -->
                    <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path d="M5 12h14"></path>
                      <path d="M12 5l7 7-7 7"></path>
                    </svg>
                  </a>
                  
                  <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                    <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                      <circle cx="12" cy="12" r="3"></circle>
                    </svg>1.2K
                  </span>
                  <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                    <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                      <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                    </svg>6
                  </span>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

templates/landing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="text-gray-700 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/moun.jpg' %}">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
        Rk Wanderlust Journeys
      </h1>
      <p class="mb-8 leading-relaxed">
          
Embark on a journey with us as we help you Explore, Dream, and Discover. Your adventure begins with our expertise by your side.
      </p>
      <div class="flex justify-center">
        <a href="{% url 'dashboard' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
          Check Destinations
        </a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
{% load static %}

<header class="text-gray-700 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a href="{% url 'dashboard' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <img class="w-10 h-10 bg-gray-300 rounded-full flex-shrink-0" src="{% static 'images/moun.jpg' %}" alt="">
        <span class="ml-3 text-xl">RK World</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      
        <a href="{% url 'dashboard' %}" class="mr-5 hover:text-gray-900">Destinations</a>
  
        {% if not request.user.is_authenticated %}

          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">signup</a>
        
        {% else %}
        {% if request.user.is_organisor %}
          <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agent</a>
        {% endif %}
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>

        {% endif %}
      </nav>

      {% if request.user.is_authenticated %}
        <p> Logged in as: {{ request.user.username }} &nbsp;
        <!-- {% if request.user.is_organisor %}
         Organisor &nbsp;
        {% else %}
         agent &nbsp;</p
        {% endif %} -->
        <a href="{% url 'logout' %}" class=" ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% endif %}
    </div>
  </header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>