destination/urls.py
from django.urls import path
from .views import (
    DestinationAddView,
    DestinationDetail,
    DestinationUpdate,
    DestinationDelete,
    )


app_name="destination"

urlpatterns=[

    path("create/",DestinationAddView.as_view(),name="destination-create"),
    path("<int:pk>/",DestinationDetail.as_view(),name="destination-detail"),
    path("<int:pk>/update/",DestinationUpdate.as_view(),name="destination-update"),
    path("<int:pk>/delete/",DestinationDelete.as_view(),name="destination-delete")
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView,
    LeadDetailView,

    LeadUpdateView,
    LeadDeleteView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    LeadRegisterView,

    )
app_name="leads"

urlpatterns=[

path('',LeadListView.as_view(), name='lead-list'),
path('<int:pk>/',LeadDetailView.as_view(), name='lead-detail'),
path('<int:pk>/register/',LeadRegisterView.as_view(), name='lead-register'),
path('<int:pk>/update',LeadUpdateView.as_view(), name='lead-update'),
path('<int:pk>/delete',LeadDeleteView.as_view(), name='lead-delete'),

path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name='assign-agent'),



path('categories/',CategoryListView.as_view(),name='category-list'),
path('categories/<int:pk>/',CategoryDetailView.as_view(),name='category-detail'),
path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='lead-category-update'),
path('creategories/<int:pk>/update',CategoryUpdateView.as_view(), name='category-update'),
path('create-category/',CategoryCreateView.as_view(), name='category-create'),
path('categories/<int:pk>/delete',CategoryDeleteView.as_view(), name='category-delete'),


]

# using name - its like name given to the url. so where we need to mention this url we can use the name in place of the url.
# /leads/create = lead_create -> without this if we did any change in url we need to chamge the url in every place.
# /leads-YT/create now we need to change this url every where because /leads/create is not same as /leads-YT/create,
# with using name we can just udate at one place and the name value will get updated in every palce.9

travel/urls.py
from django.contrib import admin
from django.contrib.auth.views import (LoginView,LogoutView,PasswordResetView, 
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView,
)

from django.urls import path
from leads.views import (
LandingPageView,
SignupView,
)

from destination.views import DashboardView

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name="landing-page"),
    path('dashboard/',DashboardView.as_view(), name="dashboard"),
    path('leads/',include('leads.urls', namespace="leads")),
    path('signup/',SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('agents/',include('agents.urls',namespace="agents")),
    path('reset-password/',PasswordResetView.as_view(),name='reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name='password_reset_done'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    
    path('destination/',include('destination.urls', namespace="destination")),



]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    path('/leads',include('leads.urls', namespace="leads")) this means if we request /leads than it will start looking for url in leads.url folder.

destination/models.py
from django.db import models

# Create your models here.
from django.conf import settings

class Destination(models.Model):
    status=[('Open','Open'),('Close','Close')]
    place_name=models.CharField(max_length=30)
    place_picture=models.ImageField(null=True, blank=True,upload_to="profile_pictures/")
    place_description = models.TextField(max_length=200)
    place_status=models.CharField(max_length=10,choices=status,default="Open")

    def __str__(self):
        return f"{self.place_name}"
    
   

destination/forms.py
from django import forms

from django.contrib.auth import get_user_model
from .models import Destination

User=get_user_model()

class DestinationForm(forms.ModelForm):
    class Meta:
        model = Destination
        fields=(
            'place_name',
            'place_description',
            'place_picture',
            'place_status'
        )

destination/views.py
from typing import Any
from django.shortcuts import reverse
from django.views.generic import (
   ListView,
   CreateView,
   DetailView,
   UpdateView,
   DeleteView)
from agents.mixins import OragniserLoginRequiredMixin

from .models import Destination
from .forms import DestinationForm
from django.conf import settings


# Create your views here.
class DashboardView(ListView):
   template_name="dashboard.html"
   context_object_name="destinations"
   queryset=Destination.objects.all()


class DestinationAddView(OragniserLoginRequiredMixin,CreateView):
   template_name="destination/add_destination.html"
   form_class=DestinationForm
   
   def get_success_url(self):
      return reverse("dashboard")



class DestinationDetail(DetailView):
   template_name="destination/detination_detail.html"
   context_object_name="destination"

   def get_queryset(self):
         pk=self.kwargs["pk"]
         return Destination.objects.filter(pk=pk)


class DestinationUpdate(OragniserLoginRequiredMixin,UpdateView):
      template_name="destination/destination_update.html"
      form_class=DestinationForm

      def get_success_url(self):
         return reverse("dashboard")
      
      def get_queryset(self):
         pk=self.kwargs["pk"]
         return Destination.objects.filter(pk=pk)
   
class DestinationDelete(OragniserLoginRequiredMixin,DeleteView):
   template_name="destination/destination_delete.html"
   
   def get_success_url(self):
      return reverse("dashboard")
   
   def get_queryset(self):
      pk=self.kwargs["pk"]
      return Destination.objects.filter(pk=pk)
   

destination/templates/destination/add_destination.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'dashboard' %}" >Go back to Destinations</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-3xl text-gray-800">Add destination</h1>
    </div>
    <form method="post" class="mt-5" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- {{ form.as_p }} -->
      {{ form|crispy }}
      <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 font rounded-md"  style="font-family: 'Arial', sans-serif;">Submit</button>
    </form>

</div>

{% endblock content%}

destination/templates/destination/destination_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'destination:destination-update' destination.pk %}">Go back to leads</a>
    </div>
    
    <h1 class="py-3 text-2xl text-gray-800">Are you sure you want to delete this destination?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 font rounded-md"  style="font-family: 'Arial', sans-serif;">Submit</button>
        </form>
</div>

{% endblock content%}d

destination/templates/destination/destination_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'dashboard' %}" >Go back to Destinations</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-3xl text-gray-800">Update {{ destination.place_name }} destination</h1>
    </div>
    <form method="post" class="mt-5" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- {{ form.as_p }} -->
      {{ form|crispy }}
      <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 font rounded-md"  style="font-family: 'Arial', sans-serif;">Submit</button>
    </form>
    <div class="mt-5 py-5 border-t border-gray-200">
        <a href="{% url 'destination:destination-delete' destination.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
            Delete
        </a>
    </div>

</div>

{% endblock content%}

destination/templates/destination/detination_detail.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap -m-4">
        <div class="lg:w-1/3 lg:mb-0 mb-6 p-4">
          <div class="h-full text-center">
            <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="https://dummyimage.com/302x302">
            <p class="leading-relaxed">Nestled amidst lush green valleys and towering peaks, Mount Serenity is a tranquil haven for nature lovers and adventure seekers alike. Located in the heart of the Serene Valley, this majestic mountain offers breathtaking panoramic views of the surrounding landscape. Visitors can embark on exhilarating hiking trails that wind through ancient forests, where cascading waterfalls and colorful wildflowers adorn the path. For the more adventurous souls, rock climbing and mountain biking present thrilling challenges against the backdrop of serene vistas. As the sun sets behind the peaks, the tranquil ambiance of Mount Serenity provides the perfect setting for a peaceful evening picnic, where families and friends can unwind and marvel at the beauty of nature.</p>
            <span class="inline-block h-1 w-10 rounded bg-indigo-500 mt-6 mb-4"></span>
            <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">Mount Serenity:</h2>
          
          </div>
        </div>
        <div class="lg:w-1/3 lg:mb-0 mb-6 p-4">
          <div class="h-full text-center">
            <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="https://dummyimage.com/300x300">
            <p class="leading-relaxed">Hiking: Explore scenic trails and discover hidden gems within the mountainous terrain.
              Rock Climbing: Test your skills and conquer challenging rock faces under the guidance of experienced climbers.
              Mountain Biking: Feel the rush of adrenaline as you navigate rugged trails and winding paths.
              Picnicking: Relax and rejuvenate amidst the beauty of nature while enjoying a picnic with loved ones.
              Wildlife Spotting: Observe diverse flora and fauna in their natural habitat, including colorful birds and elusive wildlife.
              Photography: Capture stunning landscapes and picturesque views from various vantage points along the mountain trails.</p>
            <span class="inline-block h-1 w-10 rounded bg-indigo-500 mt-6 mb-4"></span>
            <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">Activities:</h2>
          
          </div>
        </div>
        <div class="lg:w-1/3 lg:mb-0 p-4">
          <div class="h-full text-center">
            <img alt="testimonial" class="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100" src="https://dummyimage.com/305x305">
            <p class="leading-relaxed">Serene Valley Lookout: Enjoy panoramic views of the entire valley from this scenic viewpoint located at the summit of Mount Serenity.
              Whispering Waterfalls: Discover hidden waterfalls tucked away in the heart of the forest, offering a serene escape from the hustle and bustle of everyday life.
              Ancient Ruins: Explore ancient ruins and archaeological sites scattered throughout the mountain, providing a glimpse into the region's rich history and cultural heritage.
              Serenity Lake: Relax by the tranquil waters of Serenity Lake, where visitors can indulge in fishing, boating, and leisurely walks along the shore.
              Serenity Peak Observatory: Visit the observatory at the peak of Mount Serenity for unparalleled stargazing opportunities and celestial views amidst the clear night sky.
              </p>
            <span class="inline-block h-1 w-10 rounded bg-indigo-500 mt-6 mb-4"></span>
            <h2 class="text-gray-900 font-medium title-font tracking-wider text-sm">Tourist Attractions:</h2>
            
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content%}